version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: oauth-mongodb
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - oauth-network

networks:
  oauth-network:
    driver: bridge

volumes:
  mongodb_data:
